# Utilities that control the generation of identifiers.


class IdentifierGenerator:

    def __init__(self, obfuscate: bool = False):
        self.obfuscate = obfuscate

    def throwaway(self):
        """
        Generate a throwaway identifier for a variable whose liveness will
        never interfere with another variable generated by `throwaway()`.
        """

        return '__'
